# Generated by Django 3.2.12 on 2024-06-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_topic_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ManyToManyField(null=True, to='profiles.TestQuestion')),
            ],
        ),
    ]
