# Generated by Django 3.2.12 on 2022-11-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_analyticslog_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('Development', 'Development'), ('Online', 'Online'), ('Offline', 'Offline'), ('Error', 'Error')], default='Development', max_length=20),
        ),
    ]
