# Generated by Django 3.2.12 on 2024-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_testseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
