# Generated by Django 3.2.12 on 2024-06-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_testquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testseries',
            name='question',
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='options',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ManyToManyField(null=True, to='profiles.TestQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='testseries',
            name='tests',
            field=models.ManyToManyField(null=True, to='profiles.Test'),
        ),
    ]
