# Generated by Django 3.2.12 on 2022-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_chatbot_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='logs',
            field=models.ManyToManyField(blank=True, to='profiles.AnalyticsLog'),
        ),
    ]
