# Generated by Django 3.2.12 on 2022-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_chatbot_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
