# Generated by Django 3.2.12 on 2024-06-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20240620_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='solutionVideo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
