# Generated by Django 3.2.12 on 2022-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_chatbot_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='avatar',
            field=models.FileField(default='avatars/chicken.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='caching',
            field=models.BooleanField(default=False),
        ),
    ]
