# Generated by Django 3.2.12 on 2024-06-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_testquestion_solutionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempted',
            field=models.ManyToManyField(null=True, related_name='attemptedQuestions_profiles', to='profiles.TestQuestion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarked',
            field=models.ManyToManyField(null=True, related_name='bookmarkedQuestions_profiles', to='profiles.TestQuestion'),
        ),
    ]
