# Generated by Django 3.2.12 on 2022-12-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20221128_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='tokenID',
            field=models.CharField(default='', max_length=300),
        ),
    ]
