# Generated by Django 3.2.12 on 2024-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20240620_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='level',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=200),
        ),
    ]
