# Generated by Django 3.2.12 on 2024-06-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_testquestion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=models.ManyToManyField(null=True, related_name='topics_subjects', to='profiles.Topic'),
        ),
    ]
