# Generated by Django 3.2.12 on 2022-12-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_chatbot_tokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chatbotHostData',
            field=models.TextField(default=''),
        ),
    ]
