# Generated by Django 3.2.12 on 2022-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_chatbot_chatbothostdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticslog',
            name='sessionID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
