# Generated by Django 3.2.12 on 2024-06-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_subject_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='typeof',
            field=models.CharField(choices=[('11', 'Numerical - Easy'), ('12', 'Numerical - Hard'), ('21', 'Theory - Easy'), ('22', 'Theory - Hard')], default='11', max_length=200),
        ),
    ]
