# Generated by Django 3.2.12 on 2022-12-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_analyticslog_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticslog',
            name='sessionID',
        ),
    ]
