# Generated by Django 3.2.12 on 2024-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_testquestion_typeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='momentumPoints',
            field=models.IntegerField(default=0),
        ),
    ]
