# Generated by Django 3.2.12 on 2024-06-23 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_momentumpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='testseries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='testInformation',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
