# Generated by Django 3.2.12 on 2024-06-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20240623_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalsimulation',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.subject'),
        ),
    ]
