# Generated by Django 3.2.12 on 2024-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_practicalsimulation_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='testsAttempted',
            field=models.ManyToManyField(null=True, to='profiles.Test'),
        ),
    ]
