# Generated by Django 3.2.12 on 2022-11-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='brief',
            field=models.TextField(default='', max_length=150),
        ),
    ]
