# Generated by Django 3.2.12 on 2022-11-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='background',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
