# Generated by Django 3.2.12 on 2022-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background',
            field=models.FileField(blank=True, default='avatar/chicken.jpg', upload_to=''),
        ),
    ]
