# Generated by Django 3.2.12 on 2022-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
