# Generated by Django 3.2.12 on 2022-11-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='background',
        ),
    ]
