# Generated by Django 3.2.12 on 2024-06-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='background',
            field=models.FileField(default=None, upload_to='blog'),
        ),
    ]
