# Generated by Django 3.2.12 on 2024-06-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='background',
        ),
    ]
